### ISSUE TITLE
The application doesn't start on macOS Sequoia

### ISSUE THREAD

**Issue by jalzur** [mateo0023/supernote-tool-rs#3]
I tried this in Sonoma and Sequoia using an Apple Silicon M2. I tried to open and got an error such as:
> "Supernote Tool Rust.app" is damaged and can't be opened. You should move it to the Trash.

So I tried to remove it from the quarantine using the command:
> xattr -dr com.apple.quarantine <path_to_app>

After that, I tried to execute it again and I got a different error:
> Supernote Tool Rust quit unexpectedly.

<img width="249" alt="Screenshot 2024-10-15 at 22 13 03" src="https://github.com/user-attachments/assets/9ba716ef-313a-4276-9d20-86f4e18f909e">
<img width="252" alt="Screenshot 2024-10-15 at 22 14 28" src="https://github.com/user-attachments/assets/a5a6f6a9-db50-478d-b139-9710b247578c">

**Comment by mateo0023** [comment]
Thanks for reporting. Have you tried building from source?

The way for me to replicate the issue for me was to download the app (or simply remove it from my mac and re-downloading).

While I work on solving it, you could try building the bundle from source on your device.

**Comment by mateo0023** [comment]
Update. I updated the [release (v1.0.2)](https://github.com/mateo0023/supernote-tool-rs/releases/tag/v1.0.2) to a signed version and that should work (still need to need to remove the quarantine attribute `xattr -rd com.apple.quarantine /path/to/AppName.app`).

I will not notarize the app, as that requires a subscription to the Apple Developer Program and it's simply not worth it for $99/year for the project at this time.

**Comment by jalzur** [comment]
Hi, I've just tested again and I still have the same error. I've just checked the crash report and found the next reason:

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libpotrace.0.dylib
Referenced from: <EFFF33D0-3CA2-3527-8848-100206E1D17D> /private/var/folders/*/Supernote Tool Rust.app/Contents/MacOS/supernote-tool-rs
Reason: tried: '/opt/homebrew/*/libpotrace.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libpotrace.0.dylib' (no such file), '/opt/homebrew/*/libpotrace.0.dylib' (no such file)
(terminated at launch; ignore backtrace)
```

It seems that the `libpotrace` lib needs to be installed to run the application. In the Readme it says:
> For development (not needed if using a pre-compiled binary)
> 
> Rust 1.54 or later
> Cargo (Rust’s package manager)
> Potrace C library: This project requires the Potrace C library to be installed.
> Additional dependencies as listed in Cargo.toml.

So I supposed that the potrace was only needed for development. 
After installing it (`brew install potrace`) the application works fine.
